"use client";
// import type { Metadata } from "next";
import "./css/globals.css";
import { noto, poppins } from "./lib/fonts";
import { FooterAppComponent } from "./components/Footer";
import { SearchProvider } from "./hooks/searchContext";

// export const metadata: Metadata = {
//   title: "Georum by Will • Home",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en-us" dir="ltr" className={poppins.className}>
      <SearchProvider>
        <body className={poppins.className}>
          {children}
          <FooterAppComponent />
        </body>
      </SearchProvider>
    </html>
  );
}